"use client";

import { useState, useEffect } from "react";
import api from "@/utils/api";

interface MedicalRecord {
    id: number;
    visitDate: string;
    diagnosis: string;
    prescription: string;
    reportFileURL: string | null;
    hospital: { id: number; hospitalName: string };
}

const RISK_STYLE: Record<string, { bg: string; color: string; label: string }> = {
    high: { bg: "rgba(239,68,68,0.1)", color: "#f87171", label: "HIGH RISK" },
    medium: { bg: "rgba(234,179,8,0.1)", color: "#facc15", label: "MODERATE" },
    low: { bg: "rgba(34,197,94,0.1)", color: "#4ade80", label: "LOW RISK" },
};
const SCORE_COLOR = (s: number) => s >= 75 ? "#16a34a" : s >= 50 ? "#ca8a04" : "#dc2626";

export default function DoctorAISummary({ patientId, patientName }: { patientId?: number; patientName?: string }) {
    const [records, setRecords] = useState<MedicalRecord[]>([]);
    const [ai, setAi] = useState<any>(null);
    const [loadingRecords, setLoadingRecords] = useState(false);
    const [loadingAi, setLoadingAi] = useState(false);
    const [err, setErr] = useState("");

    useEffect(() => {
        if (!patientId) { setRecords([]); setAi(null); return; }
        setLoadingRecords(true); setErr("");
        api.get(`/doctors/patients/${patientId}/records`)
            .then((r) => { setRecords(r.data); })
            .catch((e) => setErr(e?.response?.data?.message || "Access denied or failed to load records."))
            .finally(() => setLoadingRecords(false));
    }, [patientId]);

    useEffect(() => {
        if (!records || records.length === 0) { setAi(null); return; }
        let mounted = true;
        setLoadingAi(true);
        fetch("/api/analyze-records", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ records })
        })
            .then(async (r) => {
                const d = await r.json();
                if (!r.ok) throw new Error(d.message || "Failed to analyze records");
                if (mounted) { setAi(d); setLoadingAi(false); }
            })
            .catch((e) => {
                if (mounted) {
                    setErr(e.message || "AI Analysis failed.");
                    setLoadingAi(false);
                }
            });
        return () => { mounted = false; };
    }, [records]);

    if (!patientId) return (
        <div style={{ padding: 40, textAlign: "center", color: "var(--text-secondary)" }}>
            <div style={{ fontSize: "3rem", marginBottom: 12 }}>🤖</div>
            <div style={{ fontWeight: 600, marginBottom: 8 }}>No patient selected</div>
            <div style={{ fontSize: "0.88rem" }}>Use Patient Search to select a patient with approved access first.</div>
        </div>
    );

    if (loadingRecords || loadingAi) return (
        <div style={{ padding: 60, textAlign: "center", color: "var(--text-secondary)" }}>
            <svg className="animate-spin" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="#a78bfa" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ margin: "0 auto 16px" }}><path d="M21 12a9 9 0 1 1-6.219-8.56" /></svg>
            <div>{loadingRecords ? "Fetching patient records…" : "AI is analyzing medical history…"}</div>
        </div>
    );

    if (err) return <div style={{ padding: 24, background: "rgba(239,68,68,0.1)", border: "1px solid rgba(239,68,68,0.2)", borderRadius: 10, color: "#fca5a5" }}>🔒 {err}</div>;

    if (!ai) return <div style={{ padding: 20, color: "var(--text-secondary)" }}>No records available for AI analysis.</div>;

    const card = { background: "rgba(255,255,255,0.03)", border: "1px solid var(--border)", borderRadius: 12, padding: "24px" };
    const hdr = { fontWeight: 700, fontSize: "0.95rem", color: "#fff", marginBottom: 16, display: "flex", alignItems: "center", gap: 8 };
    const risk = RISK_STYLE[ai.riskLevel] || RISK_STYLE.low;

    return (
        <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
            <div style={{ fontWeight: 700, color: "#fff" }}>AI Summary for: <span style={{ color: "#a78bfa" }}>{patientName}</span></div>

            <div style={{ padding: "10px 14px", background: "rgba(59,130,246,0.08)", border: "1px solid rgba(59,130,246,0.15)", borderRadius: 8, fontSize: "0.82rem", color: "#93c5fd" }}>
                🤖 Generated by AI based on {records.length} patient records. Use clinical judgment alongside this summary.
            </div>

            {/* Score + Risk Grid */}
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 }}>
                <div style={{ ...card, textAlign: "center" }}>
                    <div style={{ fontSize: "0.75rem", fontWeight: 700, color: "var(--text-secondary)", textTransform: "uppercase", marginBottom: 16 }}>Patient Vitality Score</div>
                    <div style={{ position: "relative", width: 100, height: 100, margin: "0 auto 12px" }}>
                        <svg viewBox="0 0 36 36" style={{ width: "100%", height: "100%", transform: "rotate(-90deg)" }}>
                            <circle cx="18" cy="18" r="15.9" fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="3" />
                            <circle cx="18" cy="18" r="15.9" fill="none" stroke={SCORE_COLOR(ai.healthScore)} strokeWidth="3"
                                strokeDasharray={`${ai.healthScore} ${100 - ai.healthScore}`} strokeLinecap="round" style={{ transition: "stroke-dasharray 1s ease" }} />
                        </svg>
                        <div style={{ position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center" }}>
                            <span style={{ fontSize: "1.6rem", fontWeight: 800, color: SCORE_COLOR(ai.healthScore) }}>{ai.healthScore}</span>
                        </div>
                    </div>
                    <div style={{ fontSize: "0.82rem", color: "var(--text-secondary)" }}>out of 100</div>
                </div>
                <div style={{ ...card, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 12, ...{ background: risk.bg } }}>
                    <div style={{ fontSize: "2rem" }}>{risk.color === "#f87171" ? "🔴" : risk.color === "#facc15" ? "🟡" : "🟢"}</div>
                    <div style={{ fontWeight: 800, fontSize: "1.1rem", color: risk.color }}>{risk.label}</div>
                    <div style={{ fontSize: "0.82rem", color: risk.color, opacity: 0.8, textAlign: "center" }}>Based on {records.length} records</div>
                </div>
            </div>

            {/* Predictive Health Risks */}
            {ai.predictiveRisks && (
                <div style={card}>
                    <h4 style={hdr}>
                        <svg width="20" height="20" fill="none" stroke="#f43f5e" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 12h-4l-3 9L9 3l-3 9H2" /></svg>
                        <span style={{ marginLeft: 8 }}>Predictive Health Risks</span>
                    </h4>

                    <div style={{ marginBottom: 20, padding: "12px 16px", background: "rgba(244, 63, 94, 0.1)", border: "1px solid rgba(244, 63, 94, 0.2)", borderRadius: 8, color: "#fda4af", fontSize: "0.9rem", lineHeight: 1.5 }}>
                        <strong>AI Prediction:</strong> {ai.predictiveRisks.riskContext}
                    </div>

                    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 20 }}>
                        {/* Diabetes Risk */}
                        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                            <div style={{ display: "flex", justifyContent: "space-between", fontSize: "0.85rem", color: "#e2e8f0", fontWeight: 600 }}>
                                <span>Diabetes</span>
                                <span style={{ color: ai.predictiveRisks.diabetes > 50 ? "#f43f5e" : "#fbbf24" }}>{ai.predictiveRisks.diabetes}%</span>
                            </div>
                            <div style={{ height: 8, background: "rgba(255,255,255,0.1)", borderRadius: 4, overflow: "hidden" }}>
                                <div style={{ height: "100%", width: `${ai.predictiveRisks.diabetes}%`, background: ai.predictiveRisks.diabetes > 50 ? "#f43f5e" : "#fbbf24", borderRadius: 4, transition: "width 1s ease-in-out" }} />
                            </div>
                        </div>

                        {/* Cardiac Risk */}
                        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                            <div style={{ display: "flex", justifyContent: "space-between", fontSize: "0.85rem", color: "#e2e8f0", fontWeight: 600 }}>
                                <span>Cardiac Issues</span>
                                <span style={{ color: ai.predictiveRisks.cardiac > 50 ? "#f43f5e" : "#fbbf24" }}>{ai.predictiveRisks.cardiac}%</span>
                            </div>
                            <div style={{ height: 8, background: "rgba(255,255,255,0.1)", borderRadius: 4, overflow: "hidden" }}>
                                <div style={{ height: "100%", width: `${ai.predictiveRisks.cardiac}%`, background: ai.predictiveRisks.cardiac > 50 ? "#f43f5e" : "#fbbf24", borderRadius: 4, transition: "width 1s ease-in-out" }} />
                            </div>
                        </div>

                        {/* Kidney Risk */}
                        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                            <div style={{ display: "flex", justifyContent: "space-between", fontSize: "0.85rem", color: "#e2e8f0", fontWeight: 600 }}>
                                <span>Kidney Issues</span>
                                <span style={{ color: ai.predictiveRisks.kidney > 50 ? "#f43f5e" : "#fbbf24" }}>{ai.predictiveRisks.kidney}%</span>
                            </div>
                            <div style={{ height: 8, background: "rgba(255,255,255,0.1)", borderRadius: 4, overflow: "hidden" }}>
                                <div style={{ height: "100%", width: `${ai.predictiveRisks.kidney}%`, background: ai.predictiveRisks.kidney > 50 ? "#f43f5e" : "#fbbf24", borderRadius: 4, transition: "width 1s ease-in-out" }} />
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* Chronic conditions */}
            <div style={card}>
                <h4 style={hdr}>📊 Detected Chronic Conditions</h4>
                {!ai.chronicConditions?.length ? <p style={{ color: "var(--text-secondary)", margin: 0, fontSize: "0.9rem" }}>No major chronic conditions detected.</p> : (
                    <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                        {ai.chronicConditions.map((c: string) => (
                            <span key={c} style={{ padding: "6px 16px", borderRadius: 6, background: "rgba(234,179,8,0.1)", border: "1px solid rgba(234,179,8,0.2)", color: "#facc15", fontSize: "0.85rem", fontWeight: 700 }}>{c}</span>
                        ))}
                    </div>
                )}
            </div>

            {/* Medications */}
            {ai.topMeds?.length > 0 && (
                <div style={card}>
                    <h4 style={hdr}>💊 High Frequency Medications</h4>
                    <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
                        {ai.topMeds.map(([med, count]: [string, number]) => (
                            <div key={med} style={{ display: "flex", alignItems: "center", gap: 12 }}>
                                <div style={{ flex: 1, color: "#e2e8f0", fontSize: "0.9rem", textTransform: "capitalize" }}>{med}</div>
                                <div style={{ width: 120, height: 7, background: "rgba(255,255,255,0.1)", borderRadius: 4 }}>
                                    <div style={{ height: "100%", width: `${Math.min(100, count * 33)}%`, background: "#3b82f6", borderRadius: 4 }} />
                                </div>
                                <div style={{ fontSize: "0.82rem", color: "var(--text-secondary)", width: 32, textAlign: "right" }}>{count}×</div>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Prescription Insights */}
            {ai.prescriptionInsights?.length > 0 && (
                <div style={card}>
                    <h4 style={hdr}>🔍 Detailed Prescription Insights</h4>
                    <div style={{ display: "grid", gridTemplateColumns: "1fr", gap: 16 }}>
                        {ai.prescriptionInsights.map((pi: any, idx: number) => (
                            <div key={idx} style={{ padding: 16, background: "rgba(255,255,255,0.02)", borderRadius: 10, border: "1px solid rgba(255,255,255,0.05)" }}>
                                <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 12, alignItems: "flex-start" }}>
                                    <div>
                                        <div style={{ fontSize: "1rem", fontWeight: 700, color: "#a78bfa" }}>{pi.medication}</div>
                                        <div style={{ fontSize: "0.8rem", color: "var(--text-secondary)" }}>{pi.dosage} • {pi.frequency}</div>
                                    </div>
                                    <div style={{ padding: "4px 10px", borderRadius: 6, background: "rgba(167,139,250,0.1)", color: "#a78bfa", fontSize: "0.7rem", fontWeight: 700, textTransform: "uppercase" }}>Active Ingredient Insight</div>
                                </div>
                                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 }}>
                                    <div>
                                        <div style={{ fontSize: "0.7rem", color: "var(--text-secondary)", textTransform: "uppercase", marginBottom: 4, fontWeight: 700 }}>Clinical Purpose</div>
                                        <div style={{ fontSize: "0.85rem", color: "#e2e8f0", lineHeight: 1.4 }}>{pi.purpose}</div>
                                    </div>
                                    <div>
                                        <div style={{ fontSize: "0.7rem", color: "#f87171", textTransform: "uppercase", marginBottom: 4, fontWeight: 700 }}>Possible Side Effects</div>
                                        <div style={{ fontSize: "0.85rem", color: "#fca5a5", lineHeight: 1.4 }}>{pi.possibleSideEffects}</div>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Risk alerts */}
            {ai.suggestions?.length > 0 && (
                <div style={card}>
                    <h4 style={hdr}>⚠️ Clinical Recommendations</h4>
                    <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
                        {ai.suggestions.map((s: string, i: number) => (
                            <div key={i} style={{ display: "flex", gap: 10, padding: "10px 14px", background: "rgba(255,255,255,0.03)", borderRadius: 8, border: "1px solid var(--border)" }}>
                                <span style={{ color: "#60a5fa", flexShrink: 0 }}>›</span>
                                <span style={{ fontSize: "0.88rem", lineHeight: 1.6, color: "#e2e8f0" }}>{s}</span>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Essential Findings */}
            {ai.essentialFindings?.length > 0 && (
                <div style={card}>
                    <h4 style={hdr}>📌 Other Essential Findings</h4>
                    <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
                        {ai.essentialFindings.map((f: string, i: number) => (
                            <div key={i} style={{ display: "flex", gap: 10, padding: "10px 14px", background: "rgba(255,255,255,0.03)", borderRadius: 8, border: "1px solid var(--border)" }}>
                                <span style={{ color: "#34d399", flexShrink: 0 }}>✓</span>
                                <span style={{ fontSize: "0.88rem", lineHeight: 1.6, color: "#e2e8f0" }}>{f}</span>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Treatment History Timeline */}
            {ai.treatmentHistory?.length > 0 && (
                <div style={card}>
                    <h4 style={hdr}>📅 Treatment & Medication Summary</h4>
                    <div style={{ position: "relative", paddingLeft: 16 }}>
                        <div style={{ position: "absolute", left: 0, top: 4, bottom: 4, width: 2, background: "rgba(255,255,255,0.1)" }} />
                        <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
                            {ai.treatmentHistory.map((th: any, i: number) => (
                                <div key={i} style={{ position: "relative" }}>
                                    <div style={{ position: "absolute", left: -21, top: 2, width: 12, height: 12, borderRadius: "50%", background: "#a78bfa", border: "2px solid #1e1e2d" }} />
                                    <div style={{ fontSize: "0.82rem", color: "#a78bfa", fontWeight: 700, marginBottom: 4, letterSpacing: "0.05em", textTransform: "uppercase" }}>{th.date}</div>
                                    <div style={{ fontSize: "0.95rem", color: "#fff", fontWeight: 600, marginBottom: 8 }}>{th.treatment}</div>
                                    {th.medicines?.length > 0 && (
                                        <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
                                            {th.medicines.map((m: string, mi: number) => (
                                                <span key={mi} style={{ padding: "4px 10px", borderRadius: 4, background: "rgba(59,130,246,0.1)", border: "1px solid rgba(59,130,246,0.2)", color: "#60a5fa", fontSize: "0.75rem", fontWeight: 600 }}>
                                                    💊 {m}
                                                </span>
                                            ))}
                                        </div>
                                    )}
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
